"""Seed realistic Sri Lankan school data and coherent wellbeing evidence.

Two things make this more than a name generator.

**The evidence is generated by the risk network itself.** Rather than sprinkling
independent random values across 24 variables -- which would produce students whose
transport burden, access barrier and attendance contradict each other -- this module
walks the network in topological order and samples each variable from its own CPD
given the values already drawn for its parents. ``Sector`` is pinned from the school
and ``Grade_Band`` from the class, so an estate school really does produce the
transport and resourcing pattern the model expects.

That makes the demonstration cohort internally consistent. It does **not** make it
evidence about anything: records sampled from assumed parameters can only reproduce
those assumptions (REPORT.md section 7). The dataset is labelled accordingly.

**A student's academic weakness follows from their circumstances.** The mastery
penalty handed to the academic generator is derived from the same evidence draw, so a
learner who studies alone in an under-resourced school is the learner whose concept
scores are weak -- the two halves of the system describe one child, not two.
"""

from __future__ import annotations

import json
import random
import unicodedata
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

import numpy as np

from app.db import models
from app.db.models import utcnow
from app.risk import dropout_ews_bn as bn

# Variables a school could plausibly have written down about a child. Everything else
# in the network is a modelling construct that gets inferred, not recorded.
RECORDABLE_CIRCUMSTANCES: tuple[str, ...] = (
    "Economic_Strain",
    "Parent_Education",
    "Parent_Availability",
    "Neuro_Type",
    "Child_Labour_Household_Duties",
    "Transport_Burden",
    "Food_Health_Burden",
    "Home_Educational_Support",
    "WASH_Quality",
    "Sensory_Environment",
    "School_Accommodation",
    "Bullying_Social_Exclusion",
    "Teacher_Resource_Adequacy",
)

# Always recorded: these three plus Grade_Band fully determine the outcome.
REGISTER_FIELDS: tuple[str, ...] = (
    "Previous_Attendance",
    "Current_Attendance",
    "School_Engagement",
)

STRUCTURAL_FIELDS: tuple[str, ...] = ("Sector", "Grade_Band")

# Share of recordable circumstances deliberately left blank per student, so the
# "what to find out next" panel has something real to ask for.
UNRECORDED_SHARE = 0.22

# How much each adverse circumstance drags concept mastery down. These are demo
# weights for coherence between the two halves of the system, not model parameters.
ACADEMIC_PENALTY_WEIGHTS: dict[tuple[str, str], float] = {
    ("Home_Educational_Support", "Limited"): 0.10,
    ("Teacher_Resource_Adequacy", "Limited"): 0.08,
    ("Economic_Strain", "High"): 0.05,
    ("Child_Labour_Household_Duties", "High"): 0.06,
    ("Bullying_Social_Exclusion", "High"): 0.04,
    ("School_Accommodation", "Inadequate"): 0.05,
    ("Previous_Attendance", "Irregular"): 0.09,
    ("Current_Attendance", "Irregular"): 0.07,
    ("School_Engagement", "Low"): 0.06,
}


@dataclass
class SeededStudent:
    student: models.Student
    evidence: dict[str, str]
    recorded: dict[str, str]
    academic_penalty: float
    school_sector: str


@dataclass
class SchoolSeed:
    schools: list[models.School] = field(default_factory=list)
    terms: list[models.Term] = field(default_factory=list)
    teachers: list[models.Teacher] = field(default_factory=list)
    classes: list[models.ClassGroup] = field(default_factory=list)
    students: list[models.Student] = field(default_factory=list)
    users: list[models.User] = field(default_factory=list)
    evidence: list[models.StudentRiskEvidence] = field(default_factory=list)
    attendance: list[models.AttendanceTerm] = field(default_factory=list)
    seeded: list[SeededStudent] = field(default_factory=list)
    credentials: list[dict[str, str]] = field(default_factory=list)
    seed: int = 0


# ---------------------------------------------------------------------------
# Ancestral sampling from the risk network
# ---------------------------------------------------------------------------


class AncestralSampler:
    """Draws a full, internally consistent evidence set from the network's own CPDs.

    Walks nodes in topological order; each node is drawn from its conditional
    distribution given the states already drawn for its parents. Variables passed in
    ``fixed`` are pinned rather than sampled.
    """

    def __init__(self, risk_model: bn.RiskModel) -> None:
        import networkx as nx

        self._model = risk_model.model
        self._order = list(nx.topological_sort(self._model))
        self._cpds = {cpd.variable: cpd for cpd in self._model.get_cpds()}

    def sample(self, rng: random.Random, fixed: dict[str, str]) -> dict[str, str]:
        drawn: dict[str, str] = {}
        for node in self._order:
            if node in fixed:
                drawn[node] = fixed[node]
                continue
            cpd = self._cpds[node]
            # cpd.variables is [node, *parents] in the CPD's own order.
            parents = list(cpd.variables[1:])
            index: tuple[Any, ...] = (slice(None),)
            for parent in parents:
                parent_states = list(cpd.state_names[parent])
                index = index + (parent_states.index(drawn[parent]),)
            probabilities = np.asarray(cpd.values[index], dtype=float).ravel()
            total = probabilities.sum()
            if total <= 0:
                raise ValueError(f"degenerate CPD column for {node}")
            probabilities = probabilities / total
            states = list(cpd.state_names[node])
            drawn[node] = _weighted_choice(rng, states, probabilities)
        return drawn


def _weighted_choice(rng: random.Random, states: list[str], weights: np.ndarray) -> str:
    roll = rng.random()
    cumulative = 0.0
    for state, weight in zip(states, weights):
        cumulative += float(weight)
        if roll <= cumulative:
            return state
    return states[-1]


# ---------------------------------------------------------------------------
# Names
# ---------------------------------------------------------------------------


def _format_name(pool_style: str, given: dict, surname: dict) -> tuple[str, str | None]:
    """Return (english, sinhala|None) following the pool's naming convention."""
    given_en, surname_en = given["en"], surname["en"]
    given_si, surname_si = given.get("si"), surname.get("si")

    if pool_style == "surname_first":
        # Sinhala convention: family name precedes the given name.
        english = f"{surname_en} {given_en}"
        sinhala = f"{surname_si} {given_si}" if given_si and surname_si else None
    elif pool_style == "patronymic_first":
        # Tamil convention: father's name (here the family name) precedes the given name.
        english = f"{surname_en} {given_en}"
        sinhala = None
    else:  # given_first
        english = f"{given_en} {surname_en}"
        sinhala = f"{given_si} {surname_si}" if given_si and surname_si else None
    return english, sinhala


def _username(full_name: str, index: int, role_prefix: str) -> str:
    ascii_name = (
        unicodedata.normalize("NFKD", full_name).encode("ascii", "ignore").decode("ascii")
    )
    parts = [part for part in ascii_name.lower().replace(".", "").split() if part]
    stem = parts[-1] if parts else role_prefix
    return f"{role_prefix}.{stem}{index:03d}"


# ---------------------------------------------------------------------------
# Seeding
# ---------------------------------------------------------------------------


def generate_school_seed(
    *,
    roster_path: Path,
    risk_model: bn.RiskModel,
    password_hasher,
    students_per_class: int = 20,
    grades: tuple[int, ...] = (9, 10, 11),
    seed_override: int | None = None,
) -> SchoolSeed:
    roster = json.loads(roster_path.read_text(encoding="utf-8"))
    seed = seed_override if seed_override is not None else int(roster["provenance"]["seed"])
    rng = random.Random(seed)
    sampler = AncestralSampler(risk_model)
    result = SchoolSeed(seed=seed)

    for term in roster["terms"]:
        result.terms.append(
            models.Term(
                id=term["id"],
                year=term["year"],
                term_number=term["term_number"],
                starts_on=date.fromisoformat(term["starts_on"]),
                ends_on=date.fromisoformat(term["ends_on"]),
                is_current=bool(term["is_current"]),
            )
        )
    current_term = next(t for t in result.terms if t.is_current)
    previous_term = next((t for t in result.terms if not t.is_current), current_term)

    demo_password = "wellbeing2026"
    password_hash = password_hasher(demo_password)
    student_counter = 0
    teacher_counter = 0

    for school_spec in roster["schools"]:
        school = models.School(
            id=school_spec["id"],
            name=school_spec["name"],
            name_si=school_spec.get("name_si"),
            name_ta=school_spec.get("name_ta"),
            census_no=school_spec.get("census_no"),
            district=school_spec["district"],
            province=school_spec["province"],
            sector=school_spec["sector"],
            school_type=school_spec["school_type"],
            medium_primary=school_spec["medium_primary"],
        )
        result.schools.append(school)

        primary_pool = roster["name_pools"][school_spec["name_pool"]]
        secondary_pool = roster["name_pools"].get(school_spec.get("secondary_pool", ""))
        secondary_share = float(school_spec.get("secondary_share", 0.0))
        occupations = roster["guardian"]["occupations_by_sector"][school.sector]
        relationships = roster["guardian"]["relationships"]

        # --- staff -------------------------------------------------------
        school_teachers: list[models.Teacher] = []
        staff_plan = [
            ("Principal", 1),
            ("Deputy Principal", 1),
            ("School Counsellor", 1),
            ("Sectional Head", 1),
            ("Class Teacher", len(grades) * len(school_spec["class_sections"])),
            ("Subject Teacher", 4),
        ]
        for role_title, count in staff_plan:
            for _ in range(count):
                teacher_counter += 1
                pool = primary_pool
                given_bucket = "male_given" if rng.random() < 0.42 else "female_given"
                given = rng.choice(pool[given_bucket])
                surname = rng.choice(pool["surnames"])
                name_en, name_si = _format_name(pool["style"], given, surname)
                honorific = "Mr." if given_bucket == "male_given" else "Mrs."
                teacher = models.Teacher(
                    id=f"TCH-{teacher_counter:03d}",
                    school_id=school.id,
                    full_name=f"{honorific} {name_en}",
                    full_name_si=name_si,
                    role_title=role_title,
                    subjects_json=json.dumps(
                        rng.sample(["OL-MATH", "OL-SCI", "OL-ENG", "OL-ICT"], k=2)
                        if role_title in {"Class Teacher", "Subject Teacher", "Sectional Head"}
                        else []
                    ),
                    email=None,
                )
                school_teachers.append(teacher)
                result.teachers.append(teacher)

                role = "counsellor" if role_title == "School Counsellor" else "teacher"
                if role_title in {"Principal", "Deputy Principal"}:
                    role = "admin"
                username = _username(name_en, teacher_counter, "t")
                result.users.append(
                    models.User(
                        id=f"USR-T-{teacher_counter:03d}",
                        username=username,
                        password_hash=password_hash,
                        role=role,
                        display_name=teacher.full_name,
                        display_name_si=teacher.full_name_si,
                        locale="si" if school.medium_primary == "Sinhala" else "en",
                        school_id=school.id,
                        teacher_id=teacher.id,
                        is_active=True,
                        created_at=utcnow(),
                    )
                )
                result.credentials.append(
                    {
                        "role": role,
                        "username": username,
                        "password": demo_password,
                        "display_name": teacher.full_name,
                        "school": school.name,
                        "role_title": role_title,
                    }
                )

        class_teachers = [t for t in school_teachers if t.role_title == "Class Teacher"]
        class_teacher_index = 0

        # --- classes and students ---------------------------------------
        for grade in grades:
            for section in school_spec["class_sections"]:
                class_id = f"{school.id}-{grade}{section}"
                class_teacher = (
                    class_teachers[class_teacher_index % len(class_teachers)]
                    if class_teachers
                    else None
                )
                class_teacher_index += 1
                class_group = models.ClassGroup(
                    id=class_id,
                    school_id=school.id,
                    grade=grade,
                    section=section,
                    medium=school_spec["medium_by_section"][section],
                    class_teacher_id=class_teacher.id if class_teacher else None,
                )
                result.classes.append(class_group)

                grade_band = "Junior_Secondary" if grade == 9 else "OLevel_ALevel"

                for _ in range(students_per_class):
                    student_counter += 1
                    use_secondary = (
                        secondary_pool is not None and rng.random() < secondary_share
                    )
                    pool = secondary_pool if use_secondary else primary_pool
                    is_male = rng.random() < 0.49
                    given = rng.choice(pool["male_given" if is_male else "female_given"])
                    surname = rng.choice(pool["surnames"])
                    name_en, name_si = _format_name(pool["style"], given, surname)

                    evidence = sampler.sample(
                        rng,
                        fixed={"Sector": school.sector, "Grade_Band": grade_band},
                    )

                    student_id = f"STU-{student_counter:03d}"
                    birth_year = 2026 - (grade + 5)
                    relationship = rng.choice(relationships)
                    student = models.Student(
                        id=student_id,
                        full_name=name_en,
                        full_name_si=name_si,
                        cohort=f"{grade}{section}",
                        school_id=school.id,
                        class_id=class_id,
                        admission_no=f"{birth_year}/{student_counter:04d}",
                        gender="male" if is_male else "female",
                        date_of_birth=date(
                            birth_year, rng.randint(1, 12), rng.randint(1, 28)
                        ),
                        grade=grade,
                        medium=class_group.medium,
                        guardian_name=_guardian_name(rng, pool, surname, relationship),
                        guardian_relationship=relationship,
                        guardian_contact=f"07{rng.randint(0, 8)}{rng.randint(1000000, 9999999)}",
                        guardian_occupation=rng.choice(occupations),
                        distance_to_school_km=_distance_for(rng, evidence["Transport_Burden"]),
                    )
                    result.students.append(student)

                    recorded = _select_recorded(rng, evidence)
                    penalty = _academic_penalty(evidence)
                    result.seeded.append(
                        SeededStudent(
                            student=student,
                            evidence=evidence,
                            recorded=recorded,
                            academic_penalty=penalty,
                            school_sector=school.sector,
                        )
                    )

                    now = utcnow()
                    for variable, state in recorded.items():
                        result.evidence.append(
                            models.StudentRiskEvidence(
                                id=f"EV-{student_id}-{current_term.id}-{variable}"[:96],
                                student_id=student_id,
                                term_id=current_term.id,
                                variable=variable,
                                state=state,
                                source="register"
                                if variable in REGISTER_FIELDS + STRUCTURAL_FIELDS
                                else "seed",
                                recorded_by=None,
                                recorded_at=now,
                                note=None,
                            )
                        )

                    for term, attendance_state in (
                        (previous_term, evidence["Previous_Attendance"]),
                        (current_term, evidence["Current_Attendance"]),
                    ):
                        if term.id == previous_term.id and previous_term.id == current_term.id:
                            continue
                        result.attendance.append(
                            _attendance_row(rng, student_id, term, attendance_state)
                        )

                    username = _username(name_en, student_counter, "s")
                    result.users.append(
                        models.User(
                            id=f"USR-S-{student_counter:03d}",
                            username=username,
                            password_hash=password_hash,
                            role="student",
                            display_name=name_en,
                            display_name_si=name_si,
                            locale="si" if class_group.medium == "Sinhala" else "en",
                            school_id=school.id,
                            student_id=student_id,
                            is_active=True,
                            created_at=utcnow(),
                        )
                    )
                    if student_counter <= 3:
                        result.credentials.append(
                            {
                                "role": "student",
                                "username": username,
                                "password": demo_password,
                                "display_name": name_en,
                                "school": school.name,
                                "role_title": f"Grade {grade}{section}",
                            }
                        )

    return result


def _guardian_name(rng: random.Random, pool: dict, family_name: dict, relationship: str) -> str:
    """Parents and grandparents share the family name; an aunt or uncle may not."""
    given = rng.choice(pool["female_given"] if rng.random() < 0.62 else pool["male_given"])
    keeps_family_name = relationship in {"Mother", "Father", "Grandmother", "Grandfather", "Elder sister"}
    surname = family_name if keeps_family_name else rng.choice(pool["surnames"])
    name_en, _ = _format_name(pool["style"], given, surname)
    return name_en


def _distance_for(rng: random.Random, transport_burden: str) -> float:
    if transport_burden == "High":
        return round(rng.uniform(4.5, 14.0), 1)
    return round(rng.uniform(0.3, 4.0), 1)


def _select_recorded(rng: random.Random, evidence: dict[str, str]) -> dict[str, str]:
    """Structural and register fields are always known; circumstances sometimes are not."""
    recorded = {field: evidence[field] for field in STRUCTURAL_FIELDS + REGISTER_FIELDS}
    for variable in RECORDABLE_CIRCUMSTANCES:
        if rng.random() >= UNRECORDED_SHARE:
            recorded[variable] = evidence[variable]
    return recorded


def _academic_penalty(evidence: dict[str, str]) -> float:
    penalty = 0.0
    for (variable, state), weight in ACADEMIC_PENALTY_WEIGHTS.items():
        if evidence.get(variable) == state:
            penalty += weight
    return round(min(penalty, 0.34), 4)


def _attendance_row(
    rng: random.Random, student_id: str, term: models.Term, state: str
) -> models.AttendanceTerm:
    days_total = 62
    if state == "Irregular":
        present = int(days_total * rng.uniform(0.45, 0.78))
        consecutive = rng.randint(3, 9)
    else:
        present = int(days_total * rng.uniform(0.86, 0.99))
        consecutive = rng.randint(0, 2)
    return models.AttendanceTerm(
        id=f"ATT-{student_id}-{term.id}"[:64],
        student_id=student_id,
        term_id=term.id,
        days_present=present,
        days_total=days_total,
        max_consecutive_absences=consecutive,
    )


def derive_academic_performance_evidence(
    *,
    student_id: str,
    term_id: str,
    average_mastery: float | None,
) -> models.StudentRiskEvidence | None:
    """Link the academic half to the risk half.

    ``Current_Academic_Performance`` is the one signal node a school genuinely observes,
    and we already hold the evidence for it: the learner's own concept scores.
    """
    if average_mastery is None:
        return None
    state = "Low" if average_mastery < 0.60 else "Adequate"
    return models.StudentRiskEvidence(
        id=f"EV-{student_id}-{term_id}-Current_Academic_Performance"[:96],
        student_id=student_id,
        term_id=term_id,
        variable="Current_Academic_Performance",
        state=state,
        source="derived",
        recorded_by=None,
        recorded_at=utcnow(),
        note=f"Derived from mean concept mastery {average_mastery:.2f} across all subjects.",
    )
